7.x islandora 1071
Islandora/islandora_solution_pack_entities pull request #118
Opened 2017-05-10 12:25 UTC by nmader

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1071

# What does this Pull Request do?

This pull request ensures that when a function in this module implements hook_theme() that the template_preprocess hook is called to allow overriding variables further down the processing chain.

# What's new?

The function name has been changed to begin with ‘template’ instead of islandora_solution_pack_entities.

# Interested parties

@Islandora/7-x-1-x-committers

2017-05-16 12:02 UTC, willtp87 approved these changes

2017-05-23 14:16 UTC, DiegoPino requested changes

2017-05-23 14:16 UTC, DiegoPino commented on theme/theme.inc
> + * Implements template_preprocess_theme().
Is this the right hook? template_preprocess_theme().

2017-05-23 14:54 UTC, DiegoPino approved these changes
cool. Thanks

2017-05-23 18:52 UTC, merged