7.x wcag
Islandora/islandora_solution_pack_entities pull request #127
Opened 2018-05-07 17:06 UTC by MorganDawe

**JIRA Ticket**: (https://jira.duraspace.org/browse/ISLANDORA-2217)

#WCAG Islandora Solution Pack Entities

aXe accessibility engine: https://www.deque.com/axe/
Web Accessibility inititive: https://www.w3.org/WAI/intro/wcag

# What does this Pull Request do?
The goal of this pull request is to bring islandora solution pack entities into compliance with WCAG 2.0 standards.

It is important to note that this pull aims to address accessibility violations as seen by the average, non authenticated users. Administrative pages remain unaffected.

# What's new?
Adds alt attributes to the thumbnail in the templates and adds corresponding <dd> tag where applicable and a corresponding label.

# How should this be tested?

The easiest way to test these changes locally:
- install the aXe browser plugin in your browser of choice (found here: https://www.deque.com/axe/).
- Recommended: Enable the ‘AT Subtheme’ found in the Adaptive Core (https://www.drupal.org/project/adaptivetheme). This theme is the closest to matching wcag 2.0 requirements i could find.
- Run the aXe tool on a person or department page, or another wcag 2.0 compliance testing toolkit, and examine the page for WCAG 2.0 violations sourced from this modules code.

# Interested parties
Tag (@rosiel @Islandora/7-x-1-x-committers)

2018-05-11 17:28 UTC, qadan approved these changes

2018-05-30 15:49 UTC, MorganDawe commented
@rosiel @Islandora/7-x-1-x-committers Any further suggestions.

2018-06-08 13:53 UTC, MorganDawe commented
@rosiel @Islandora/7-x-1-x-committers do you think you will have time to take another peek at this sometime soon? Not trying to bug. Thank you.

2018-06-08 19:33 UTC, rosiel commented
Hey - sorry, still trying to get that release out.

2018-06-26 13:26 UTC, MorganDawe commented
@rosiel  Just a reminder that this pull is here. Thank you for taking the time to review it.

2018-07-16 20:16 UTC, DiegoPino requested changes
Tiny change. I don't see where biography thing is relevant to Wcag and what to do if label is empty == no tn_alt

2018-07-16 20:16 UTC, DiegoPino commented on theme/islandora-person.tpl.php
> +    <h2 class="bio"><?php print t('Biography'); ?></h2>
This is new? Is the biography related to WCAG? If so, where is this defined?

2018-07-19 17:45 UTC, MorganDawe commented
Removed the BIO label.

2018-07-23 18:22 UTC, MorganDawe commented
@DiegoPino Just a reminder this pull is here, if you have any further suggestions.

2018-07-23 18:23 UTC, DiegoPino approved these changes

2018-07-23 18:23 UTC, DiegoPino commented
OK, cool. Seeing the changes. Approved, merging in 24. Thanks (sorry, was not reading all my notifications, my fault)

2018-07-24 18:12 UTC, DiegoPino requested changes
tiny little change.. sorry man

2018-07-24 18:12 UTC, DiegoPino commented on theme/islandora-dept.tpl.php
> +      <img alt="<?php print $tn_alt;?>" id="<?php print $tn_id;?>" src="<?php print $variables['tn']; ?>"/>
sorry @MorganDawe was about to merge and saw this..:( just for the sake of consistency, could you please change $tn_alt to $variables['tn_alt', etc?
I know they get auto-magically expanded, but makes reading, customizing later much easier if referenced from  $variables array.

2018-08-14 14:11 UTC, MorganDawe commented
@DiegoPino i have updated the ```islandora-dept.tpl.php``` template to reflect the changes you suggested.

2018-08-14 14:24 UTC, DiegoPino commented
@MorganDawe ok cool. will wait for Travis to finish, thanks man!

2018-08-15 16:20 UTC, DiegoPino approved these changes

2018-08-15 16:20 UTC, DiegoPino commented
All good. Merging in 24 hours! Thanks for addressing all my concerns, i appreciate it

2018-08-28 12:07 UTC, MorganDawe commented
@DiegoPino "marco" :)

2018-08-28 12:22 UTC, merged

2018-08-28 12:22 UTC, DiegoPino commented
Polo? Merged!